### ISSUE TITLE
Add Crytic CI

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/devops#4]
Info: https://blog.trailofbits.com/2019/08/02/crytic-continuous-assurance-for-smart-contracts/

Status: Emailed Trail of Bits asking for details. Waiting for a response.

**Comment by 0xGabi** [comment]
Super interesting, do you have responses so far?

**Comment by yeqbfgxjiq** [comment]
I have not heard back. I was actually going to talk on our call today. We should decide if Crytic is something we want to pay for, and if so, then I was thinking to follow up emphasizing that if Crytic works for us we would recommend it for the broader Aragon ecosystem. I want to make sure we get a good deal tho considering that we currently have very limited resources.

**Comment by yeqbfgxjiq** [comment]
Reached out to Trail of Bits _again_ asking about CryticCI (via the CryticCI signup form), but no response... Not sure what the deal is? ~~Going to just start~~ Started just bugging the Trail of Bits team directly

**Comment by yeqbfgxjiq** [comment]
Got a response! They're going to help us get CryticCI running this week. Apparently if Slither works, then CryticCI should be easy to setup.
- https://github.com/crytic/slither
- https://blog.trailofbits.com/2019/07/03/avoiding-smart-contract-gridlock-with-slither/

**Comment by yeqbfgxjiq** [comment]
We are now official early beta testers of CryticCI!
